const CODES = {
    ROUND:'Round',
    PRINCESS:'Princess',
    EMERALD:'Emerald',
    SQUARE_EMERALD:'Square Emerald',
    ASSCHER:'Asscher',
    RADIANT:'Radiant',
    SQUARE_RADIANT:'Square Radiant',
    CUSHION:'Cushion',
    CUSHION_BRILLIANT:'Cushion Brilliant',
    CUSHION_MODIFIED:'Cushion Modified',
    PEAR:'Pear',
    OVAL:'Oval',
    MARQUISE:'Marquise',
    HEART:'Heart',
    TAPERED_BAGUETTE:'Tapered Baguette',
    BAGUETTE:'Baguette',
    EUROPEAN_CUT:'European Cut',
    OLD_MINER:'Old Miner',
    START:'Star',
    ROSE:'Rose',
    HALF_MOON:'Half Moon',
    SQUARE:'Square',
    BULLETS:'Bullets',
    TAPERED_BULLETS:'Tapered Bullets',
    TRAPEZOID:'Trapezoid',
    FLANDERS:'Flanders',
    BRIOLETTE:'Briolette',
    PENTAGONAL:'Pentagonal',
    HEXAGONAL:'Hexagonal',
    OCTAGONAL:'Octagonal',
    TRIANGULAR:'Triangular',
    TRILLIANT:'Trilliant',
    CALF:'Calf',
    SHIELD:'Shield',
    LOZENGE:'Lozenge',
    KITE:'Kite',
    CHOKI:'Choki',
    ROUND_MB:'Round MB'
}


module.exports = {
    CODES
};